[versions]
assertj = "3.27.7"
compose = "1.11.1"
kotlin = "2.4.10"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
