name: Publish

on:
  push:
    tags:
      - v**

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew :plugin:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
